using PrompterLive.Shared.Pages;

namespace PrompterLive.Shared.Settings.Models;

public sealed record SettingsPagePreferences(
    string OneDriveSyncFolder,
    bool CloudAutoSyncOnSave,
    bool CloudSyncOnStartup,
    string ScriptsLocation,
    string RecordingsLocation,
    string ExportsLocation,
    string ExportFormat,
    string RecordingsStorageLimit,
    bool FileAutoSaveEnabled,
    bool FileBackupCopiesEnabled,
    bool AutoRecordWhenStreaming,
    bool SplitRecordingHourly,
    string RecordingFolder,
    string RecordingNamingPattern,
    string RecordingContainer,
    string RecordingVideoCodec,
    string RecordingVideoResolution,
    string RecordingVideoFrameRate,
    int RecordingVideoBitrateKbps,
    string RecordingAudioCodec,
    string RecordingAudioSampleRate,
    int RecordingAudioBitrateKbps,
    string RecordingAudioChannels,
    string SelectedAiProviderId,
    string ColorScheme,
    string AccentColor,
    string TeleprompterFont,
    int TeleprompterFontSize,
    string TeleprompterTextColor,
    bool MirrorTeleprompterText,
    bool ShowWordHighlight,
    string UiDensity,
    bool ReduceMotion,
    bool ShowShortcutOverlay,
    bool ShowHeaderChrome,
    bool AmbientGradientMotion)
{
    public const string StorageKey = "prompterlive.settings-page";

    public static SettingsPagePreferences Default { get; } = new(
        OneDriveSyncFolder: "/OneDrive/Prompter",
        CloudAutoSyncOnSave: true,
        CloudSyncOnStartup: true,
        ScriptsLocation: "/Users/you/Documents/Prompter/Scripts",
        RecordingsLocation: "/Users/you/Documents/Prompter/Recordings",
        ExportsLocation: "/Users/you/Downloads",
        ExportFormat: "TPS (Native)",
        RecordingsStorageLimit: "No limit",
        FileAutoSaveEnabled: true,
        FileBackupCopiesEnabled: true,
        AutoRecordWhenStreaming: true,
        SplitRecordingHourly: false,
        RecordingFolder: "/Users/you/Documents/Prompter/Recordings",
        RecordingNamingPattern: "Script Name + Date",
        RecordingContainer: "MP4",
        RecordingVideoCodec: "H.264 (AVC)",
        RecordingVideoResolution: "Same as source",
        RecordingVideoFrameRate: "30 fps",
        RecordingVideoBitrateKbps: 8000,
        RecordingAudioCodec: "AAC",
        RecordingAudioSampleRate: "48 kHz",
        RecordingAudioBitrateKbps: 320,
        RecordingAudioChannels: "Stereo",
        SelectedAiProviderId: SettingsAiProviderIds.ClaudeApi,
        ColorScheme: "dark",
        AccentColor: "#C4A060",
        TeleprompterFont: "Inter (Default)",
        TeleprompterFontSize: 48,
        TeleprompterTextColor: "#FFFFFF",
        MirrorTeleprompterText: false,
        ShowWordHighlight: true,
        UiDensity: "default",
        ReduceMotion: false,
        ShowShortcutOverlay: true,
        ShowHeaderChrome: true,
        AmbientGradientMotion: true);
}
