namespace PrompterLive.Shared.Localization;

public enum UiTextKey
{
    DiagnosticsDismiss,
    DiagnosticsRetry,
    DiagnosticsLibrary,
    DiagnosticsFatalTitle,
    DiagnosticsFatalMessage,
    DiagnosticsRecoverableTitle,
    LibraryAllScripts,
    LibraryRecent,
    LibraryFavorites,
    LibraryFolders,
    LibraryNewFolder,
    LibrarySettings,
    LibrarySortBy,
    LibrarySortName,
    LibrarySortDate,
    LibrarySortDuration,
    LibrarySortWpm,
    LibraryCreateFolderTitle,
    LibraryCreateFolderDescription,
    HeaderSearchPlaceholder,
    HeaderNewScript,
    HeaderLearn,
    HeaderRead,
    HeaderGoLive,
    HeaderSettings,
    GoLiveHeroEyebrow,
    GoLiveHeroDescription,
    CommonName,
    CommonParent,
    CommonTopLevel,
    CommonCancel,
    CommonCreate,
    LibraryFolderPlaceholder
}
