namespace PrompterOne.Shared.Settings.Models;

public sealed record SettingsPagePreferences(
    bool AutoRecordWhenStreaming,
    bool SplitRecordingHourly,
    string RecordingFolder,
    string RecordingNamingPattern,
    string RecordingContainer,
    string RecordingVideoCodec,
    string RecordingVideoResolution,
    string RecordingVideoFrameRate,
    int RecordingVideoBitrateKbps,
    string RecordingAudioCodec,
    string RecordingAudioSampleRate,
    int RecordingAudioBitrateKbps,
    string RecordingAudioChannels,
    string ColorScheme,
    string AccentColor,
    string TeleprompterFont,
    int TeleprompterFontSize,
    string TeleprompterTextColor,
    bool MirrorTeleprompterText,
    bool ShowWordHighlight,
    string UiDensity,
    bool ReduceMotion,
    bool ShowShortcutOverlay,
    bool ShowHeaderChrome,
    bool AmbientGradientMotion,
    string? LanguageCulture)
{
    public const string StorageKey = "prompterone.settings-page";

    public static SettingsPagePreferences Default { get; } = new(
        AutoRecordWhenStreaming: true,
        SplitRecordingHourly: false,
        RecordingFolder: "Browser-local recording store",
        RecordingNamingPattern: "Script Name + Date",
        RecordingContainer: "MP4",
        RecordingVideoCodec: "H.264 (AVC)",
        RecordingVideoResolution: "Same as source",
        RecordingVideoFrameRate: "30 fps",
        RecordingVideoBitrateKbps: 8000,
        RecordingAudioCodec: "AAC",
        RecordingAudioSampleRate: "48 kHz",
        RecordingAudioBitrateKbps: 320,
        RecordingAudioChannels: "Stereo",
        ColorScheme: SettingsAppearanceValues.DarkColorScheme,
        AccentColor: SettingsAppearanceValues.DefaultAccentColor,
        TeleprompterFont: "Inter (Default)",
        TeleprompterFontSize: 48,
        TeleprompterTextColor: "#FFFFFF",
        MirrorTeleprompterText: false,
        ShowWordHighlight: true,
        UiDensity: SettingsAppearanceValues.DefaultDensity,
        ReduceMotion: false,
        ShowShortcutOverlay: true,
        ShowHeaderChrome: true,
        AmbientGradientMotion: true,
        LanguageCulture: null);
}
